# Generated by Django 5.0.14 on 2026-09-20 12:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefrigerationTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('suction_pressure', models.FloatField(help_text='Compressor suction pressure in bar')),
                ('discharge_pressure', models.FloatField(help_text='Compressor discharge pressure in bar')),
                ('discharge_temperature', models.FloatField(help_text='Compressor discharge / condenser inlet temperature in °C')),
                ('condenser_outlet_temp', models.FloatField(help_text='Condenser outlet / expansion inlet temperature in °C')),
                ('evaporator_inlet_temp', models.FloatField(help_text='Expansion outlet / evaporator inlet temperature in °C')),
                ('evaporator_outlet_temp', models.FloatField(help_text='Evaporator outlet / suction line temperature in °C')),
                ('compressor_status', models.CharField(default='OFF', help_text='RUNNING / STARTING / STOPPED / OFF', max_length=30)),
                ('condenser_fan_status', models.CharField(default='IDLE', help_text='ACTIVE / IDLE / OFF', max_length=30)),
                ('evaporator_fan_status', models.CharField(default='IDLE', help_text='ACTIVE / IDLE / OFF', max_length=30)),
                ('system_status', models.CharField(default='STOPPED', help_text='RUNNING / STARTING / STOPPED', max_length=30)),
                ('fault_type', models.CharField(blank=True, default='None', help_text='Active fault description if any', max_length=100, null=True)),
            ],
            options={
                'db_table': 'refrigeration_telemetry',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='refrigerati_timesta_fb3bea_idx')],
            },
        ),
    ]
